### ISSUE TITLE
DB Setup

### ISSUE THREAD

**Issue by andresfm8** [andresfm8/roadtripplus#5]
Create data models and endpoints to interact with the db

**Comment by frankie-mur** [comment]
# Tasks
---
- [x]  Create Home route
- [x]  Create Login route
- [x]  Store Users into db (working on)
- [x]  Store Users -> Destinations into db (working on)
- [ ]  Update Delete routes  (working on)

**Comment by andresfm8** [comment]
Delete routes won't be implemented as for now
